### PR TITLE
Improved subject line, plus signatures and such

### PR DESCRIPTION
**Pull request by timshadel**
Mimic vim a bit by allowing the entire subject line to be highlighted, and only mark the extra chars as warning or errors.  Highlight the Signed-off-by as well.

### CODE REVIEW

**Comment by adamv** [comment]
FWIW, I like having the whole line lit up as a warning; I use the char position in the editor to know how many chars to delete.

**Comment by timshadel** [comment]
Looks like it's also pulled my later work into this pull request. I've added some default styles for the subject and list of files changed, as well as called out the branch to which you'll be committing.

**Comment by timshadel** [comment]
@adamv, I can see that. I use the block of red to gauge how much I care about editing the subject -- small block no big deal, big block I actually edit it.  It's the way other editors (like vim) highlight git commits, so I've emulated it here (used it for a long time, actually).

I wonder if there's an easy way to tag the whole line with a marker in addition to what I've got that would allow for both preferences to be accommodated.

**Comment by jcf** [comment]
I like the signed-off-by highlighting.

Thoughts on the subject line?

**Comment by timshadel** [comment]
OK.  This latest arrangement should allow for either approach to subject highlighting. What do you think @adamv? Does this help you out? :-)

**Comment by timshadel** [comment]
@jcf - I think this is ready to go. Let me know if you'd like any other changes before pulling it.

**Comment by jcf** [comment]
Merged in to master.

**Pull request merged**
